[build]
  functions = "functions/"
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "/calendar"
  to = "/calendar"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}